defaults:
  - encoder: w2v2_fullft
  - model: baseline
  - graph: fixed_gat
  - _self_

find_unused_parameters: true

weights_path: /data/home/borodin_sam/another_workspace/AASIST3/weights/train/FINAL/model.safetensors
pretrained_repo_id: null
weights_cache_dir: weights

projection:
  enabled: false
  hidden_dim: 256
  dim: 128
  dropout: 0.1

batch_size: 128
num_workers: 24
shuffle: false
max_val_batches: 10

data:
  asvspoof2021_df:
    root_dir: /data/additional/DATASETS/audio/asvspoof2021_DF/ASVspoof2021_DF_eval/flac
    meta_path: /data/additional/DATASETS/audio/asvspoof2021_DF/trial_metadata.txt

  asvspoof2021_la:
    root_dir: /data/additional/DATASETS/audio/ASVspoof2021_LA_eval/flac
    meta_path: /data/additional/DATASETS/audio/ASVspoof2021_LA_eval/trial_metadata.txt

  asvspoof5_test:
    root_dir: /data/additional/DATASETS/audio/asvspoof5/flac_E_eval
    meta_path: /data/additional/DATASETS/audio/asvspoof5/ASVspoof5.eval.track_1.tsv

  asvspoof2019_eval:
    root_dir: /data/additional/DATASETS/audio/asvspoof2019/LA/ASVspoof2019_LA_eval/flac
    meta_path: /data/additional/DATASETS/audio/asvspoof2019/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
