defaults:
  - encoder: hubert_fullft
  - model: mamba
  - graph: fixed_graphsage
  - loss: ce_supcon
  - _self_
  - optional experiment: null

find_unused_parameters: true

num_epochs: 40
checkpoint_interval: 5  
max_train_batches: 1000
max_val_batches: 200
gradient_accumulation_steps: 2

train_batch_size: 8
val_batch_size: 16
num_workers: 8

learning_rate: 1e-4

projection:
  enabled: false
  hidden_dim: 256
  dim: 128
  dropout: 0.1

export:
  weights_path: /data2/autoNav/storage/.fine/.sp/weights/train/FINAL/model_fsage_mamba_supcon.safetensors
  repo_id: null

augmentation:
  two_views: true

project_name: "antispoof"
run_name: "check_multigpu"
tensorboard_dir: ./runs

checkpoint_base_path: /data2/autoNav/storage/.fine/.sp/weights/train_fsage_mamba_supcon
resume_from_checkpoint: null

data:
  asvspoof5_train:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/flac_T/flac_T
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/ASVspoof5.train.metadata.txt

  asvspoof2019_train:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_train/flac
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt

  mlaad:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/MLAAD

  m_ailabs:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/M_AILABS_stub

  asvspoof5_dev:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/flac_D/flac_D
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/ASVspoof5.dev.trial.txt

  asvspoof2019_dev:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_dev/flac
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt

  asvspoof2021_df:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof2021_DF/ASVspoof2021_DF_eval/flac
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof2021_DF/trial_metadata.txt

  asvspoof2021_la:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/ASVspoof2021_LA_eval/flac
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/ASVspoof2021_LA_eval/trial_metadata.txt

  asvspoof5_test:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/flac_E_eval/flac_E_eval
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof5/ASVspoof5.eval.track_1.tsv

  asvspoof2019_eval:
    root_dir: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_eval/flac
    meta_path: /data2/autoNav/storage/.fine/.sp/audio_2/asvspoof_2019/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
