name: wav2vec2
model_name: facebook/wav2vec2-large-xlsr-53
load_pretrained: true
normalize_waveform: true
cache_dir: weights
freeze_strategy: none
unfreeze_last_n_layers: 24
layer_aggregation: last
mean_last_k: 4

